version: '3'
services: 
    app :
        container_name: numer
        restart: always
        build: .
        ports: 
             - '3000:3000'
        links: 
             - api
    api :
        container_name: api
        build: ./backend
        ports: 
             - '5000:5000'
    #     depends_on: 
    #         - mongo
  
    # mongo:
    #     container_name: mongo
    #     image: mongo
    #     ports:
    #        - "27017:27017"
    
        
       
      
      

    